import os

# Environment variable for MultiQueryRetriever
MULTI_QUERY_RETRIEVER_TEMPERATURE = float(os.environ.get("MULTI_QUERY_RETRIEVER_TEMPERATURE", "0.0"))
MULTI_QUERY_RETRIEVER_DEPLOYMENT_NAME = os.environ.get("MULTI_QUERY_RETRIEVER_DEPLOYMENT_NAME", "gpt-35-turbo")


# Environment variables for ConversationalRetrievalChain LLMChain
CONVERSATIONAL_RETRIEVAL_LLM_CHAIN_TEMPERATURE = float(
    os.environ.get("CONVERSATIONAL_RETRIEVAL_CHAIN_TEMPERATURE", "0.3")
)
CONVERSATIONAL_RETRIEVAL_LLM_CHAIN_DEPLOYMENT_NAME = os.environ.get(
    "CONVERSATIONAL_RETRIEVAL_LLM_CHAIN_DEPLOYMENT_NAME", "gpt-35-turbo-16k"
)

# Environment variables for ConversationalRetrievalChain Load QA Chain
CONVERSATIONAL_RETRIEVAL_LOAD_QA_CHAIN_TEMPERATURE = float(
    os.environ.get("CONVERSATIONAL_RETRIEVAL_LOAD_QA_CHAIN_TEMPERATURE", "0.5")
)
CONVERSATIONAL_RETRIEVAL_LOAD_QA_CHAIN_DEPLOYMENT_NAME = os.environ.get(
    "CONVERSATIONAL_RETRIEVAL_LOAD_QA_CHAIN_DEPLOYMENT_NAME", "gpt-4-32k"
)

SERVICE_MAINTENANCE_BANNER_STATUS = os.environ.get("SERVICE_MAINTENANCE_BANNER", "False") == "True"
