---
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - python -m pip install poetry
      - python -m poetry config virtualenvs.create false
    post_install:
      # Install dependencies with 'docs' dependency group
      # https://python-poetry.org/docs/managing-dependencies/#dependency-groups
      - poetry install --only=docs,dev

sphinx:
  configuration: docs/conf.py
