# syntax=quay.io/astronomer/airflow-extensions:latest
#for some reason pypandoc is not installing without the buildkit

FROM quay.io/astronomer/astro-runtime:9.1.0-base

COPY include/airflow_provider_weaviate-0.0.1-py3-none-any.whl /tmp
