<script lang="ts">
  import * as Card from "$lib/components/ui/card";
  import { Skeleton } from "$lib/components/ui/skeleton";
  import SvelteMarkdown from "svelte-markdown";
  import { Person, Laptop, Check, Cross2 } from "radix-icons-svelte";
  import * as HoverCard from "$lib/components/ui/hover-card";
  import Button from "../ui/button/button.svelte";
  import { enhance } from "$app/forms";
  import { fade } from "svelte/transition";
  import { onMount } from "svelte";

  let hasReacted: boolean | undefined = undefined;

  export let content: string;
  export let type: "ai" | "human";
  export let highlight: boolean = false;
  export let additional_kwargs: { [key: string]: string } = {};
  export let showFeedback: boolean = false;
  export let requestUuid: string | undefined = undefined;
  export let isLoading: boolean = false;

  const hasReactedKey = `request:${requestUuid}:reacted`;

  onMount(() => {
    // use localStorage to track if the user has reacted to this request
    hasReacted = localStorage.getItem(hasReactedKey) === "true" ? true : false;
  });

  let timestamp: string | undefined = additional_kwargs.ts || undefined;

  // TODO: move this to the backend
  const translatedContent = content.replace(/<@U05A2NM0MDX>/g, "@AskAstro");
</script>

<Card.Root class="p-2 {highlight && 'border-4 border-purple-800'}">
  <Card.Content class="p-2">
    <Card.Title class="text-sm flex items-center">
      {#if type === "ai"}
        <Laptop class="w-4 h-4 mr-2 flex-shrink-0" />
      {:else}
        <Person class="w-4 h-4 mr-2 flex-shrink-0" />
      {/if}
      {#if type === "ai"}
        <HoverCard.Root>
          <HoverCard.Trigger class="text-black">Astro</HoverCard.Trigger>
          <HoverCard.Content>
            This message was generated by an AI model and may not be accurate.
          </HoverCard.Content>
        </HoverCard.Root>

        {#if additional_kwargs?.ask_astro_request_uuid}
          <a
            href={`/requests/${additional_kwargs.ask_astro_request_uuid}`}
            class="text-purple-600 ml-2">See the original request</a
          >
        {/if}
      {:else}
        Human
      {/if}

      <div class="flex-auto" />

      {#if timestamp}
        <span class="text-xs font-normal"
          >{new Date(parseFloat(timestamp) * 1000).toLocaleString()}</span
        >
      {/if}
    </Card.Title>

    <div class="pt-2 overflow-x-scroll">
      {#if isLoading}
        <div class="flex flex-col gap-2">
          <Skeleton class="w-full h-4" />
          <Skeleton class="w-full h-4" />
          <Skeleton class="w-full h-4" />
        </div>
      {:else}
        <SvelteMarkdown source={translatedContent} />
      {/if}
    </div>

    {#if showFeedback && requestUuid && hasReacted !== undefined}
      <div class="text-gray-600">
        {#if hasReacted === false}
          <div class="flex gap-2 items-center" in:fade>
            <div class="flex-auto" />
            <p class="mr-4">Is this correct?</p>
            <form
              action="?/feedback"
              method="post"
              use:enhance={() => {
                return async () => {
                  hasReacted = true;
                  localStorage.setItem(hasReactedKey, "true");
                };
              }}
            >
              <input type="hidden" name="request_uuid" value={requestUuid} />
              <input type="hidden" name="is_correct" value="true" />
              <Button size="icon" type="submit">
                <Check class="w-4 h-4" />
              </Button>
            </form>
            <form
              action="?/feedback"
              method="post"
              use:enhance={() => {
                return async () => {
                  hasReacted = true;
                  localStorage.setItem(hasReactedKey, "true");
                };
              }}
            >
              <input type="hidden" name="request_uuid" value={requestUuid} />
              <input type="hidden" name="is_correct" value="false" />
              <Button size="icon" type="submit" variant="secondary">
                <Cross2 class="w-4 h-4" />
              </Button>
            </form>
          </div>
        {:else}
          <div class="flex mt-4" transition:fade>
            <div class="flex-auto" />
            <p>Thanks for the feedback!</p>
          </div>
        {/if}
      </div>
    {/if}
  </Card.Content>
</Card.Root>
